मन्त्रसमीकरणम्
vvasuki/vedAH pull request #11
Opened 2020-12-23 16:34 UTC by Veerasimha

2020-12-26 05:50 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/1.md
> +त॒न् मे॑ जिन्वतम् ।
कुतोऽत्र तच्छब्दे सन्नतरः??

2020-12-26 05:52 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/1.md
> +त॒न् मे॑ जिन्वतम् ।
अत्रापि तच्छब्दस्वरः

2020-12-26 16:03 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/1.md
> +त॒न् मे॑ जिन्वतम् ।
मे इत्यत्र स्वरितं दृष्ट्वा तकारे सन्नतरः स्यात् इति चिन्तितम् । तच्छब्दे तकारः उदात्त इति क्रमपाठं दृष्ट्वा अवगतम् । इदानीं सन्नतरस्वरः निष्कासितः

2020-12-26 16:04 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/1.md
> +त॒न् मे॑ जिन्वतम् ।
पूर्ववत् अत्रापि अन्यत्रापि सन्नतरः निष्कासितः

2020-12-27 14:34 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/1.md
> +त॒न् मे॑ जिन्वतम् ।
स्वरितं दृष्ट्वा प्राक्तन उदात्तः स्याद् इत्य् अवागमिष्यद् भवान् (क्रमपाठापेक्षां विना)। कुतः स्वरितम् अशङ्कत?

2020-12-27 14:42 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/2/5.md
> +मि॒त्रेण॑+ ए॒व य॒ज्ञस्य॒ स्व्-इ॑ष्टꣳ श॒म॒य॒न्ति॒ , वरु॑णेन॒ दुर्-इ॑ष्टम् +++(शमयन्ति )+++ ।
अत्र शमयन्ति॒ इत्येव स्यात्। कुत इति विचिन्त्य वदतु।

2020-12-27 14:45 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/5.md
> +"भुव॒" +इत्य् आ॑ह।
अत्र सन्धिनिमित्तके विसर्गलोपे सम्पादिते ऽपि कुतः खलु सन्धिचिह्नम् + इति?

2020-12-27 14:45 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/5.md
> +सु॒व॒र्गाय॒ वा ए॒ष लो॒कायाधी॑यते यद् आ॑हव॒नीयस् , सु॒व॒र्ग ए॒वास्मै॑ लो॒के वा॒चस् स॒त्यꣳ सर्व॑म् आप्नोति ।
सुव॒र्ग ए॒वास्मै॑ इत्येव स्यात्। कुत इति विचिन्त्य वदतु।

2020-12-27 14:46 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/5.md
>  यत् त्रे॒धा ऽग्निर् आ॑धी॒यते᳚ म॒हि॒मान॑म् ए॒वास्य॒ तद् व्यू॑हति, शान्त्या॒ अप्र॑दाहाय ।
अत्रापि म॒हि॒मान॑म् इत्यस्मिन् दोषः। क इति वदतु। कुत इति च।

2020-12-27 14:49 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/2/1.md
> +#### विभक्तमन्त्रः
कोऽयम् विभक्तमन्त्र इति निर्देशः? `## मूलम्` इति कुतो न?

2020-12-27 14:50 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/6/10.md
> +अ॒पᳶ परि॑षिञ्चति रु॒द्रस्या॒न्तर्‌हि॑त्यै ।
कुतोऽत्र रेफस्य पृथग्दर्शने श्रमः?

2020-12-27 14:51 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/6/10.md
> +"त्र्य॑म्बकय्ँ यजामहे" इत्य् आ॑ह ।
कुसन्धिः

2020-12-27 14:53 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/3/1.md
> +यस्यै॒वँव्वि॒दुषो॒ ग्रहा॑ गृ॒ह्यन्ते᳚ ।
मूलं कुतो गृह्यमाणम्?? अनुनासिकस्थाने दोषो ऽनुवर्तते ऽत्र। अन्यत्राप्य् अन्विष्य निवारयतु।

2020-12-28 08:01 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/2/5.md
> +मि॒त्रेण॑+ ए॒व य॒ज्ञस्य॒ स्व्-इ॑ष्टꣳ श॒म॒य॒न्ति॒ , वरु॑णेन॒ दुर्-इ॑ष्टम् +++(शमयन्ति )+++ ।
वरुणेन इत्यत्र रुकारे स्वरितः  वर्तते । तत्पूर्वं सन्नतरेण भाव्यम् । शमयन्ति इत्यस्य तिङन्तत्वात्  तत्र अन्त्ये सन्नतरेण भाव्यम् , नतु सर्वाक्षरेषु । सर्वाक्षरेषु सन्नतरत्वं केवलं पदपाठमात्रे भविष्यति । वाक्यमध्ये न भवति इति

2020-12-28 08:03 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/5.md
> +"भुव॒" +इत्य् आ॑ह।
भुव इत्यत्र विसर्गः लुप्तः । तत्स्पष्टतायै सन्धिचिन्हं स्थापितम् । भुवे इत्यपि भवेत् , अथवा भुव इत्यपि । सन्धिचिन्हस्थापनेन अत्र नूनं विसर्गसन्धिरिति स्पष्टं भवतीति मया चिन्तितम्

2020-12-28 08:08 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/5.md
> +सु॒व॒र्गाय॒ वा ए॒ष लो॒कायाधी॑यते यद् आ॑हव॒नीयस् , सु॒व॒र्ग ए॒वास्मै॑ लो॒के वा॒चस् स॒त्यꣳ सर्व॑म् आप्नोति ।
पदपाठदशायां , वाक्यारम्भे वा सुवर्गशब्दे आदौ सन्नतरस्वरः । वाक्यमध्ये चेत् सुवर्ग इत्यत्र सुकार उदात्तः । नामत्वात् इति

2020-12-28 08:12 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/5.md
>  यत् त्रे॒धा ऽग्निर् आ॑धी॒यते᳚ म॒हि॒मान॑म् ए॒वास्य॒ तद् व्यू॑हति, शान्त्या॒ अप्र॑दाहाय ।
महिमानम् इत्यत्र मकार उदात्तः । अतः मकारे सन्नतरो न युक्तः इति ज्ञातम् । कुत इति न ज्ञातम् । आधीयते इत्यत्र अन्त्ये स्वरितसद्भावात् अग्रिमाक्षरे सन्नतरत्वं न युक्तम् इति वा । न स्पष्टमवगतम्

2020-12-28 08:17 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/2/1.md
> +#### विभक्तमन्त्रः
अयं भागः न मूलेन सह योजितः । १-६ पर्यन्तं मूलं योजितमासीत् । अतः एवं दृश्यते ।

2020-12-28 08:20 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/6/10.md
> +"त्र्य॑म्बकय्ँ यजामहे" इत्य् आ॑ह ।
अत्र सन्धिचिन्हं न स्थापितम् । यजामहे इति शब्दस्वरूपस्पष्टप्रतिभासनाय कोटेशन् चिन्हमध्ये स्थापितम् । यजामह इत्याह इत्येव वरं वा

2020-12-28 08:21 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/3/1.md
> +यस्यै॒वँव्वि॒दुषो॒ ग्रहा॑ गृ॒ह्यन्ते᳚ ।
मूलं रा टेक्ट् तः स्वीकृतम् । अत्र सर्वत्र अनुनासिकचिन्हानि एवमेव वर्तते

2020-12-28 12:08 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/1.md
> +त॒न् मे॑ जिन्वतम् ।
असकृद् अत्र भवच्चिन्तने दोषो भवति। अनुपेक्ष्योत्तरतु।

2020-12-28 12:09 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/2/5.md
> +मि॒त्रेण॑+ ए॒व य॒ज्ञस्य॒ स्व्-इ॑ष्टꣳ श॒म॒य॒न्ति॒ , वरु॑णेन॒ दुर्-इ॑ष्टम् +++(शमयन्ति )+++ ।
" तत्पूर्वं सन्नतरेण भाव्यम् । " इति न साधु। कुत इति वदतु।

2020-12-28 12:10 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/5.md
> +"भुव॒" +इत्य् आ॑ह।
सन्धिचिह्ने स्थापितेऽपि भुवे इति वा भुवः इति वा न स्पष्टीभवति। ततो नैतद् युक्तम्। एतादृशे स्थले मास्तु सन्धिचिह्नम्।

2020-12-28 12:13 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/5.md
> +सु॒व॒र्गाय॒ वा ए॒ष लो॒कायाधी॑यते यद् आ॑हव॒नीयस् , सु॒व॒र्ग ए॒वास्मै॑ लो॒के वा॒चस् स॒त्यꣳ सर्व॑म् आप्नोति ।
भवता साधु नावगतम्। सुवर्ग इत्यत्र कतमो वर्ण उदात्त इति मूलस्य दर्शनेन स्पष्टीभवति। ननु गकार एवोदात्तः!

एवन्तर्हि सुकारे कुतो न स्यात् सन्नतरचिह्नम्? सन्नतरस्वरितचिह्नयोर् अभावे संहितायाम् वर्ण उदात्त एवेति ज्ञेयो वा? अथवा सन्नतरोदात्तस्वरितैकश्रुतिषु कश्चिद् अन्यतमो ऽपि स्यत्?

2020-12-28 12:14 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/5.md
> +"भुव॒" +इत्य् आ॑ह।
अत्राप्य् उत्तरलेखनं न विस्मरतु। यावद् अहं सूत्रं न पिदधामि मत्सन्देशो न कश्चनानुत्तीर्णस् तिष्ठेत्।

2020-12-28 12:16 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/6/10.md
> +"त्र्य॑म्बकय्ँ यजामहे" इत्य् आ॑ह ।
आम् - यजामह इत्याह इत्येव लेख्यम्। अथवा सन्धिचिह्नं स्थापनीयम्। नान्यथैवं सन्धिविच्छेदो योग्यः संहितायाम्।

2020-12-28 12:17 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/3/1.md
> +यस्यै॒वँव्वि॒दुषो॒ ग्रहा॑ गृ॒ह्यन्ते᳚ ।
कुतो दुष्टस्रोतोऽवलम्बनम्?? परिष्कृतपाठो ऽत्रैव खलु निक्षिप्तः परिसरे? स एवोपादेयः। एवंविधदोषो न स्याद् यथान्यत्र, तथा विधेयम्।

2020-12-28 12:19 UTC, vvasuki commented
प्रत्युत्तरलेखने पुनरेव स्मारणम् - यावद् अहं सूत्रं न पिदधामि मत्सन्देशो न कश्चनानुत्तीर्णस् तिष्ठेत्। अन्यथा "गृहीतं वा? सुगृहीतं वा? पुनश् चक्रवद् दोषो वर्तेत वा?" इत्येवं सन्देहा जायेरन्।

2020-12-28 12:28 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/2/5.md
> +मि॒त्रेण॑+ ए॒व य॒ज्ञस्य॒ स्व्-इ॑ष्टꣳ श॒म॒य॒न्ति॒ , वरु॑णेन॒ दुर्-इ॑ष्टम् +++(शमयन्ति )+++ ।
अस्मात्पाठकैः तथा पाठितम्। तदेव मनसि आरूढं वर्तते ।उच्चैरुदात्तः इत्यनुसारेण यत्र ऊर्ध्वाङ्कनं भवति तत्र उदात्तस्वरः इति पूर्वं बाल्ये अधीतमासीत् । इदमिदानीमेव उदात्तस्वरितौ व्यत्यस्तौ इति ज्ञातमपि तत् कदाचित् विस्मरति । अत एवं दोषः । 
किञ्च सन्नतरत्वे अन्यत् कारणं न स्पष्टं जातम्

2020-12-28 12:29 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/5.md
> +"भुव॒" +इत्य् आ॑ह।
एतादृशस्थलेषु सन्धिचिह्नं निष्कासयामि

2020-12-28 12:33 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/5.md
> +सु॒व॒र्गाय॒ वा ए॒ष लो॒कायाधी॑यते यद् आ॑हव॒नीयस् , सु॒व॒र्ग ए॒वास्मै॑ लो॒के वा॒चस् स॒त्यꣳ सर्व॑म् आप्नोति ।
सत्यम् । अत्रापि स्वरसञ्चारः कथमिति न स्पष्टम् । क्रमपाठं दृष्ट्वा पदानां स्वरं कथमिति ज्ञात्वा ऐदम्पर्यन्तं स्थापयन्नस्मि ।

2020-12-28 12:34 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/6/10.md
> +"त्र्य॑म्बकय्ँ यजामहे" इत्य् आ॑ह ।
यजामह इत्येव समीकरोमि ।

2020-12-28 12:39 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/3/1.md
> +यस्यै॒वँव्वि॒दुषो॒ ग्रहा॑ गृ॒ह्यन्ते᳚ ।
सर्वत्र परिष्करोमि ।

2020-12-28 12:49 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/5.md
> +"भुव॒" +इत्य् आ॑ह।
ॐ - परीक्षान्ते ऽत्र "सर्वत्र समीकृतम्" इति सूचयतु।

2020-12-28 12:56 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/5.md
> +सु॒व॒र्गाय॒ वा ए॒ष लो॒कायाधी॑यते यद् आ॑हव॒नीयस् , सु॒व॒र्ग ए॒वास्मै॑ लो॒के वा॒चस् स॒त्यꣳ सर्व॑म् आप्नोति ।
क्रमपाठं दृष्ट्वाऽपि व्याकरणे सन्देहे सति पृच्छतु नाम। सन्देहास्पदं न कुर्यात्।

मूलं योजयत्व् अत्र सर्वत्रान्यत्र च। ततो भाषावहै।

2020-12-28 12:56 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/3/1.md
> +यस्यै॒वँव्वि॒दुषो॒ ग्रहा॑ गृ॒ह्यन्ते᳚ ।
ॐ - परीक्षान्ते ऽत्र "सर्वत्र समीकृतम्" इति सूचयतु।

2020-12-28 13:00 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/2/5.md
> +मि॒त्रेण॑+ ए॒व य॒ज्ञस्य॒ स्व्-इ॑ष्टꣳ श॒म॒य॒न्ति॒ , वरु॑णेन॒ दुर्-इ॑ष्टम् +++(शमयन्ति )+++ ।
उदात्तः प्रधानः स्वरः (“अनुदात्तं पदम् एकवर्जम्।")। उदात्तात्पूर्वं सन्नतरः, पश्चात् स्वरितः।  एवन्तर्हि प्रायेण सर्वत्रैवं क्रमः - 

- उदात्ताभिज्ञानम्।
- उदात्तस्थानम् आश्रित्य सन्नतरस्वरितयोर् अभिज्ञानम्।

एवन्तर्हि, सन्नतरत्वे उदात्तपूर्वता हेतुः, न "स्वरित"पूर्वता। (अथवा स्वरितशब्दस्य +असमीचीनार्थे प्रयोगो भवत क्रियमाणः।) अयं स्पष्टो वा? तथा चेत् "अत्र शमयन्ति॒ इत्येव स्यात्। कुत इति विचिन्त्य वदतु।" इति यद् उक्तम्, तत्र पुनर् उत्तरदाने प्रयतताम्।

2020-12-30 00:39 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/mula/brAhmaNam/1/1.md
> +ब्रह्म॒ सन्ध॑त्त॒न्तन्मे॑ जिन्वतम् ।
एताः सञ्चिका `mula` निष्कासनीयाः। मूलसंयोगाय https://github.com/vvasuki/vedAH/blob/master/content/taittirIyam/brAhmaNam/brAhmaNam_full.md इत्येव प्रयोक्तव्यम्। अन्यथा शुद्धतासन्देहः।

2021-01-07 15:34 UTC, vvasuki commented on content/taittirIyam/saMhitA/bhaTTa-bhAskara-bhAShyam/6/2.md
> +स याव्ँ् वन॒स्पति॒ष्वव॑स॒त् ताम् पूतु॑द्रौ॒ , यामोष॑धीषु॒ ताꣳ सु॑गन्धि॒तेज॑ने॒ , याम् प॒शुषु॒ ताम् पेत्व॑स्यान्त॒रा शृङ्गे᳚ ।
"याव्ँ्" इत्यत्र टङ्कनदोषः। सदयम् भवान् उट्टङ्कनम् अपहाय यावच्छक्यं copy-paste इति करोतु।

2021-01-07 15:35 UTC, vvasuki commented on content/taittirIyam/saMhitA/bhaTTa-bhAskara-bhAShyam/6/1.md
>  ### संयुक्तमन्त्रः
ब्राह्मणभागे `मूलम्` इत्येवास्तु निर्देशः, न तु संयुक्तमन्त्र इत्यादिकम्।

2021-01-10 22:30 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/10.md
> +यद्गार्‌ह॑पत्य॒ आज्य॑मधि॒श्रय॑न्ति॒ सम्पत्नी᳚र्या॒जय॑न्ति ।
कुतोलब्धोऽयं मूलपाठः? 

यद्गार्ह॑पत्य॒ आज्य॑मधि॒श्रय॑न्ति॒ +इति नन्व् आबहोः कालात् brAhmaNam_full इति सञ्चिकायाम् अवर्तत (रेफे भेदः)। अस्मिन् पर्याय एवम् अस्तु नाम - स्वीकृत्य स्वयम् परिवर्तयिष्यामि।

2021-01-10 22:40 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/10.md
> +यथ्स॒भायाँ᳚व्वि॒जय॑न्ते ।
अत्रापि मूलम् भो न साधु!! अनुनासिकम् ईक्षताम्। सर्वत्र सुपरिष्कृतायाः brAhmaNam_full इति सञ्चिकाया एव ग्राह्यम्। सर्वत्र परीक्ष्य परिवर्त्य +अत्र लेख्यम्। ततः परम् एव स्वरशोधने ऽस्त्व् अनुवर्तनम्।

2021-01-10 22:46 UTC, vvasuki commented on content/taittirIyam/saMhitA/bhaTTa-bhAskara-bhAShyam/6/1.md
>  ### संयुक्तमन्त्रः
संहितासञ्चिका कुतः स्पृष्टा ? यथापूर्वं विदध्यात्। सत्वरम् परिहरणीयोऽयं दोषः।

2021-01-10 22:47 UTC, vvasuki commented on content/taittirIyam/saMhitA/bhaTTa-bhAskara-bhAShyam/6/2.md
> +स याव्ँ् वन॒स्पति॒ष्वव॑स॒त् ताम् पूतु॑द्रौ॒ , यामोष॑धीषु॒ ताꣳ सु॑गन्धि॒तेज॑ने॒ , याम् प॒शुषु॒ ताम् पेत्व॑स्यान्त॒रा शृङ्गे᳚ ।
न - भवत एव दोषः - परिवर्तनस्यास्मिन्न् आकर्षणाभ्यर्थने वर्तित्वात्।

संहितासञ्चिका कुतः स्पृष्टा ? यथापूर्वं विदध्यात्। सत्वरम् परिहरणीयोऽयं दोषः।

2021-01-10 22:49 UTC, vvasuki commented on content/taittirIyam/saMhitA/bhaTTa-bhAskara-bhAShyam/6/2.md
> +स याव्ँ् वन॒स्पति॒ष्वव॑स॒त् ताम् पूतु॑द्रौ॒ , यामोष॑धीषु॒ ताꣳ सु॑गन्धि॒तेज॑ने॒ , याम् प॒शुषु॒ ताम् पेत्व॑स्यान्त॒रा शृङ्गे᳚ ।
`git checkout origin/master content/taittirIyam/saMhitA/bhaTTa-bhAskara-bhAShyam/6/2.md` इति कृत्वा यथापूर्वस्थितिं लभताम्।

2021-01-10 22:53 UTC, vvasuki commented on content/taittirIyam/saMhitA/bhaTTa-bhAskara-bhAShyam/6/1.md
>  ### संयुक्तमन्त्रः
यथापूर्व-करणायोपायो ऽत्रोक्तः - https://github.com/vvasuki/vedAH/pull/11/files#r554634920

2021-01-10 22:55 UTC, vvasuki commented
temp-सञ्चिका (यथा brAhmaNam_full-temp.md ) निष्कासनीयाः।

2021-01-10 23:03 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/5.md
> +सु॒व॒र्गाय॒ वा ए॒ष लो॒कायाधी॑यते यद् आ॑हव॒नीयस् , सु॒व॒र्ग ए॒वास्मै॑ लो॒के वा॒चस् स॒त्यꣳ सर्व॑म् आप्नोति ।
मूलानि योजितानीत्युक्तम्, भाषितञ्च। सूत्रम् एतत् पिधीयते।

2021-01-10 23:04 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/5.md
>  यत् त्रे॒धा ऽग्निर् आ॑धी॒यते᳚ म॒हि॒मान॑म् ए॒वास्य॒ तद् व्यू॑हति, शान्त्या॒ अप्र॑दाहाय ।
साधु। कुतस् तर्हि म॒हि॒मान॑म् इत्येव लिखति "महि॒मान॑म्" इत्यस्य स्थाने? एकश्रुतेर् इत्थं स्वराङ्कनम् अत्रोचितं वा?

2021-01-10 23:06 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/6.md
> + ## मूलम्
`## मन्त्रः` इति स्यात्??

2021-01-10 23:07 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/6.md
> + ## मन्त्रः
एवम् अधिकं रिक्तस्थानं न स्याद् अत्र।

2021-01-10 23:12 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/6.md
>  दे॒वा॒सु॒रास् सय्ँय॑त्ता आसन्न् ।
एवं टीकाभागरहितो `## मन्त्र`भागो न स्यात् क्वचिद् अपि। मूलाद् अध मन्त्रशेषेण सह+एव योजनीयः। तेन मूलभागेऽप्य् अस्तु पुनर्-उक्तिः

2021-01-12 03:22 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/mula/brAhmaNam/1/1.md
> +ब्रह्म॒ सन्ध॑त्त॒न्तन्मे॑ जिन्वतम् ।
mula सञ्चिकाः निष्कासिताः । ब्राह्मण- पूर्णम् इत्यतः मूलं योजयन्नस्मि

2021-01-12 03:25 UTC, Veerasimha commented on content/taittirIyam/saMhitA/bhaTTa-bhAskara-bhAShyam/6/2.md
> +स याव्ँ् वन॒स्पति॒ष्वव॑स॒त् ताम् पूतु॑द्रौ॒ , यामोष॑धीषु॒ ताꣳ सु॑गन्धि॒तेज॑ने॒ , याम् प॒शुषु॒ ताम् पेत्व॑स्यान्त॒रा शृङ्गे᳚ ।
vedAH]$ git checkout origin/master content/taittirIyam/saMhitA/bhaTTa-bhAskara-bhAShyam/6/2.md
Updated 1 path from 0bf782156
इति  फलं प्राप्तमस्ति

2021-01-12 03:30 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/10.md
> +यद्गार्‌ह॑पत्य॒ आज्य॑मधि॒श्रय॑न्ति॒ सम्पत्नी᳚र्या॒जय॑न्ति ।
पूर्वं ब्राह्मण-मूल-सञ्चिकाः विभक्ता आसन् । ततो गृहीतपाठात् अयं दोषः समजनि । इदानीं पूर्ण-ब्राह्मणपाठात् मूलसंयोजनकरणात्अयं दोषः नानुवर्तते ।

2021-01-12 03:31 UTC, Veerasimha commented
> temp-सञ्चिका (यथा brAhmaNam_full-temp.md ) निष्कासनीयाः।




मूलयोजने आनुकूल्याय अयं सृष्टः । अत्र मन्त्राणि प्रत्येकपङ्क्तौ स्थापितानि । मूलयोजनानन्तरं निष्कासयामि

2021-01-12 04:04 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/6.md
> + ## मूलम्
आम् । मन्त्रः इति समीकृतम् । hogo परिशीलनं ब्राह्मणभागेषु न कृतम् । अतः क्वचित् एवं व्यत्यासः समजनि । क्वचित्  स्वराङ्कनेपि व्यत्यासः hogo परिशीलनेन इदानीं ज्ञाlतः। समीकरोमि आर्य । क्वचित् पूर्वोत्तरमन्त्रसंयुक्तस्थलेषु स्वराङ्कनं क्वचित् त्यक्तमस्ति  इत्यपि ज्ञातमिदानीम् । तदपि परिशील्य समीकृत्य पुष् करोमि आपञ्चमसञ्चिकात्

2021-01-12 04:06 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/6.md
> + ## मन्त्रः
समीकृतं सर्वत्र । कार्यान्त्ये पुष् करोमि

2021-01-12 05:30 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/6.md
> + ## मूलम्
ॐ - समीकृत्य सूचयतु।

2021-01-12 05:31 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/10.md
> +यद्गार्‌ह॑पत्य॒ आज्य॑मधि॒श्रय॑न्ति॒ सम्पत्नी᳚र्या॒जय॑न्ति ।
पुरा योजितानाम् मूलानाम् परीक्षणं तर्हि विधेयम्। विधाय सूचयतु।

2021-01-12 05:47 UTC, vvasuki commented on content/taittirIyam/saMhitA/bhaTTa-bhAskara-bhAShyam/6/2.md
> +स याव्ँ् वन॒स्पति॒ष्वव॑स॒त् ताम् पूतु॑द्रौ॒ , यामोष॑धीषु॒ ताꣳ सु॑गन्धि॒तेज॑ने॒ , याम् प॒शुषु॒ ताम् पेत्व॑स्यान्त॒रा शृङ्गे᳚ ।
विफलस् तर्हि स प्रयत्नः। इत इव प्राचीनं पाठं गृहीत्वा सञ्चिकां यथापूर्वं कृत्वा नुदतु।

2021-01-20 06:23 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/5.md
>  यत् त्रे॒धा ऽग्निर् आ॑धी॒यते᳚ म॒हि॒मान॑म् ए॒वास्य॒ तद् व्यू॑हति, शान्त्या॒ अप्र॑दाहाय ।
महिमानम् इत्यत्र स्वरः समीकृतः । एकश्रुतेरेवं स्वराङ्कनं न समीचीनम् । उचितरीत्या स्वर अङ्कितः

2021-01-20 06:33 UTC, Veerasimha commented on content/taittirIyam/saMhitA/bhaTTa-bhAskara-bhAShyam/6/2.md
> +स याव्ँ् वन॒स्पति॒ष्वव॑स॒त् ताम् पूतु॑द्रौ॒ , यामोष॑धीषु॒ ताꣳ सु॑गन्धि॒तेज॑ने॒ , याम् प॒शुषु॒ ताम् पेत्व॑स्यान्त॒रा शृङ्गे᳚ ।
यथापूर्वं कृत्वा नुदिता । वकारे अनुनासिकचिन्हदोषसमीकरणकाले अकस्मात् अत्रापि दोषो दृष्ट इति परिहर्तुं प्रयतितमासीत् ।

2021-01-27 02:57 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/3/1.md
> +यस्यै॒वँव्वि॒दुषो॒ ग्रहा॑ गृ॒ह्यन्ते᳚ ।
अनुनासिकसमीकरणं साधितं वा?

2021-01-27 03:43 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/3/1.md
> +यस्यै॒वँव्वि॒दुषो॒ ग्रहा॑ गृ॒ह्यन्ते᳚ ।
४सञ्चिकापर्यन्तं अनुनासिकचिन्हदोषो निवारितः ।  hogo परिचालनेन ,यावत्  स्वरदोषनिवारणं सञ्चिकासु तावत्पर्यन्तं दोषः समीकृतः । अग्रेपि प्रतिसञ्चिकां hogo परिशीलनसमये यद्यवशिष्टं तदपि निवार्यते

2021-01-27 13:38 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/5.md
> +"भुव॒" +इत्य् आ॑ह।
एतच्च समीकृतम्?

2021-01-27 13:40 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/10.md
> +यद्गार्‌ह॑पत्य॒ आज्य॑मधि॒श्रय॑न्ति॒ सम्पत्नी᳚र्या॒जय॑न्ति ।
अत्र का वार्ता?

2021-01-27 13:41 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/10.md
> +यथ्स॒भायाँ᳚व्वि॒जय॑न्ते ।
अत्र समीकृतम्?

2021-01-27 13:41 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/6.md
> + ## मूलम्
??

2021-01-27 13:41 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/6.md
>  दे॒वा॒सु॒रास् सय्ँय॑त्ता आसन्न् ।
??

2021-01-27 15:09 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/5/8.md
> +###  टीका
कुतोऽत्रैवं क्रियमाणम्? #### इत्येव स्यात् खलु।

2021-01-27 15:11 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/5/8.md
> +###  टीका
अथवा `### मन्त्रः` इत्येतत् समीकरणीयम्?

2021-01-28 04:27 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/5.md
> +"भुव॒" +इत्य् आ॑ह।
आम् , समीकृतमस्ति । मदीयसङ्ग्रहे अत्र + इति चिन्हमपाकृतमस्ति । अपिचात्र अयादेशसन्धिदोष आसीत् । य ए॒तेना॒ग्निम् आ॑ध॒त्ते + ऋ॒ध्नोत्य् ए॒व । इति । (अयादेशसन्धिस्थले )अत्र इदीनीं दोषः समीकृतः । य ए॒तेना॒ग्निम् आ॑ध॒त्त  ऋ॒ध्नोत्य् ए॒व । इति । अयादेशसन्धिस्थलेषु सन्धिमकृत्वा + चिन्हं स्थापितम् ।

2021-01-28 04:34 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/6.md
> + ## मूलम्
समीकृतमस्ति

2021-01-28 04:36 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/5/8.md
> +###  टीका
मन्त्रे ## चिह्नम्
टीकायाम् ###  इति अनुवर्तते ।५-३ पर्यन्तं एवं समीकृतमस्ति

2021-01-28 04:39 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/6.md
>  दे॒वा॒सु॒रास् सय्ँय॑त्ता आसन्न् ।
अत्रापि समीकृतम् । मूलम् , मन्त्रः, टीका इति क्रमः , क्वचित् वाक्यसंयोजनस्थलेषु भिन्नमन्त्रत्वात् मूलम् - मन्त्रः, मूलं - मन्त्रः, इति निर्दिष्टमस्ति ।

2021-01-28 05:11 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/1.md
> +त॒न् मे॑ जिन्वतम् ।
एतद् अपि परिष्कृतं वेति दृष्ट्वा लिखतु।

2021-01-28 05:16 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/1.md
> +त॒न् मे॑ जिन्वतम् ।
एतत् परिष्कृतमेव वर्तते ।

2021-01-28 05:20 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/1.md
> +त॒न् मे॑ जिन्वतम् ।
१सञ्चिकादारभ्य सन्धिस्थले अन्ये केचन दोषाः इदानीं प्रतिभासन्ते । तान् समीकृत्य अनुनासिकदोषानपि परिशील्य ब्राह्मण-मूलसञ्चिकात् परिवर्त्य पुष् करोमि ।

2021-01-28 11:33 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/10.md
> +यथ्स॒भायाँ᳚व्वि॒जय॑न्ते ।
१-१० सञ्चिकासु अनुनासिक-रेफभेददोषः समीकृतः ।
किञ्च
अस॑व्व्लँयाय, स इथ्सर्व॒व्व्ँया॑नशे  इत्याद्यनेकस्थले  brAhmaNam_full सञ्चिकायाम्  अनुनासिकचिन्हदोषः दृश्यते > व्व् इत्यस्य मार्गणेनेदं ज्ञातम् ।
ब॒र्॒हिर॑ग्न॒ आज्य॑स्य वेतु रेफभेदः अत्र ।

2021-01-28 11:33 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/10.md
> +यद्गार्‌ह॑पत्य॒ आज्य॑मधि॒श्रय॑न्ति॒ सम्पत्नी᳚र्या॒जय॑न्ति ।
१-१० सञ्चिकासु परीक्षितम् । दोषः समीकृतः

2021-01-28 13:13 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/10.md
> +यथ्स॒भायाँ᳚व्वि॒जय॑न्ते ।
साधु सूचितम्।  तत्र , तथा  "ताञ्छ॒य्य्वँ॑न्त॒ उपा॑नयन्न्। " इत्यत्र शुद्धम् पाठम् मुद्रितपुस्तकय् अवलोक्य वदतु। (अन्यत्र समीकृतम् - git pull upstream master इति कृत्वा वक्तव्यम्।)

2021-01-28 13:14 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/10.md
> +यथ्स॒भायाँ᳚व्वि॒जय॑न्ते ।
(ससन्न्तररेफे चिन्ता मास्तु।)

2021-01-29 09:55 UTC, vvasuki commented on content/taittirIyam/saMhitA/bhaTTa-bhAskara-bhAShyam/6/2.md
> +2कथं तर्हि कर्तव्यमित्याह - विमुक्त इत्यादिविधिः ।। एकोनड्वान्विमुक्तः कार्यः अनागतत्वनिवृत्तये, एकमविमुक्तं कुर्यात् अविच्छेदार्थं कर्मणोऽपेक्षां द्योतयितुम् । अथास्मिन् काले आतिथ्यं गृह्णाति एवं यज
किमत्र दण्डद्वयस्थापनेन?

2021-01-29 10:05 UTC, Veerasimha commented
> temp-सञ्चिका (यथा brAhmaNam_full-temp.md ) निष्कासनीयाः





निष्कासितम्

2021-01-29 10:19 UTC, Veerasimha commented on content/taittirIyam/saMhitA/bhaTTa-bhAskara-bhAShyam/6/2.md
> +2कथं तर्हि कर्तव्यमित्याह - विमुक्त इत्यादिविधिः ।। एकोनड्वान्विमुक्तः कार्यः अनागतत्वनिवृत्तये, एकमविमुक्तं कुर्यात् अविच्छेदार्थं कर्मणोऽपेक्षां द्योतयितुम् । अथास्मिन् काले आतिथ्यं गृह्णाति एवं यज
संहितासंचिकायांं टीकायां सर्वत्र दण्दद्वयमस्ति ।  ॥ चिन्हस्थले ।।  इति आगतमस्ति । अयं regex तः जातः

2021-01-29 10:30 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/10.md
> +यथ्स॒भायाँ᳚व्वि॒जय॑न्ते ।
"ताञ्छ॒य्य्वँ॑न्त॒ उपा॑नयन्न्। इत्यत्र मुद्रितपुस्तकेपि एवमेव वर्ते । तान् शंयुवाकान्ते इति च टीका । तान् शंयु इत्यत्र श्चुत्वसन्धिः ।

2021-01-29 12:50 UTC, vvasuki commented on content/taittirIyam/saMhitA/bhaTTa-bhAskara-bhAShyam/6/2.md
> +2कथं तर्हि कर्तव्यमित्याह - विमुक्त इत्यादिविधिः ।। एकोनड्वान्विमुक्तः कार्यः अनागतत्वनिवृत्तये, एकमविमुक्तं कुर्यात् अविच्छेदार्थं कर्मणोऽपेक्षां द्योतयितुम् । अथास्मिन् काले आतिथ्यं गृह्णाति एवं यज
समीकरोतु नाम तर्हि।

अपि च "चिह्नम्" इत्येव लेखनं शुद्धम् प्रचलितोच्चारणविकारेऽपि।

2021-01-29 12:52 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/10.md
> +यथ्स॒भायाँ᳚व्वि॒जय॑न्ते ।
अस्तु तर्हि `ताञ्छ॒य्ँय्व॑न्त॒` इति शोधयतु।

"अस॑व्व्लँयाय" इत्यत्र कः पाठो दर्शितः?

2021-01-29 13:06 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/10.md
> +यथ्स॒भायाँ᳚व्वि॒जय॑न्ते ।
"अस॑व्व्लँयाय" इत्यत्र असंवलशब्दः ।  असंव्लयः अविशरणम् इति टीका । अस॑व्ँव्लयाय इति पाठ आदृतः

2021-01-29 13:29 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/10.md
> +यथ्स॒भायाँ᳚व्वि॒जय॑न्ते ।
क्षम्यताम् । मया अनुनासिकस्थानमात्रं तदा दृष्टमासीत् । सन्नतरस्थाने दोष आसीत् । "ताञ्छंय्वन्त॒ उपा॑नयन्न्। इति मुद्रितपाठः । 

स इथ्सर्व॒व्व्ँया॑नशे" इति मन्त्रः प्रायः द्वितीयाष्टके भवति । अतः तस्य अनुवाकसङ्ख्या न ज्ञायते ।

2021-01-29 16:01 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/10.md
> +यथ्स॒भायाँ᳚व्वि॒जय॑न्ते ।
अस॑व्व्लँयाय इत्यत्र मुद्रितपाठः कः?

ताञ्छ॒य्य्वँ॑न्त॒ इति मुद्रितपाठे छकारे सन्नतरो नास्ति वा?? वकारे स्वरितश् च?

2021-01-30 03:22 UTC, Veerasimha commented on content/taittirIyam/saMhitA/bhaTTa-bhAskara-bhAShyam/6/2.md
> +2कथं तर्हि कर्तव्यमित्याह - विमुक्त इत्यादिविधिः ।। एकोनड्वान्विमुक्तः कार्यः अनागतत्वनिवृत्तये, एकमविमुक्तं कुर्यात् अविच्छेदार्थं कर्मणोऽपेक्षां द्योतयितुम् । अथास्मिन् काले आतिथ्यं गृह्णाति एवं यज
समीकृतम्

2021-01-30 03:47 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/10.md
> +यथ्स॒भायाँ᳚व्वि॒जय॑न्ते ।
छकारे सन्नतरो नास्ति वकारे स्वरितो वर्तते । टेलिग्रामि चित्रं प्रेषितम्

2021-01-30 04:02 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/10.md
> +यथ्स॒भायाँ᳚व्वि॒जय॑न्ते ।
चित्रे दृष्टे।

`ताञ्छय्ँय्व॑न्त॒` इत्यस्तु।  `अस॑व्व्लँयाय` इति साधु।

2021-01-30 04:05 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/10.md
> +यथ्स॒भायाँ᳚व्वि॒जय॑न्ते ।
अस॑व्व्लँयाय इत्यत्र अस॑व्व् लँयाय इति लकारे अनुनासिको दृश्यते । सकारोत्तरवकारे अनुनासिकं साधु इति भाति

2021-01-30 04:13 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/10.md
> +यथ्स॒भायाँ᳚व्वि॒जय॑न्ते ।
अस॑व्ँव्लयाय इति यथा भवता शोधितम्, तदेव साधु। मया +उपरि टङ्कनदोषः कृत आसीत्। अधुना शोधितः।

2021-01-30 04:16 UTC, Veerasimha commented
धन्योस्मि

On Sat, 30 Jan, 2021, 9:43 am Vishvas Vasuki विश्वासः, <
notifications@github.com> wrote:

> *@vvasuki* commented on this pull request.
> ------------------------------
>
> In content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/10.md
> <https://github.com/vvasuki/vedAH/pull/11#discussion_r567194152>:
>
> >
> -यथ् स॒भाया᳚व्ँ वि॒जय॑न्ते तेन॒ सो᳚ ऽस्या॒भीष्ट॑ᳶ प्री॒तः ।
> -####  टीका
> +###  टीका
> +यदाहवनीये जुह्वति । इन्द्रादिभ्योपि । अत्रापि होमग्रहणं प्रदर्शनमिध्मसन्नहनादीनां प्रक्षेपस्य ।
> +## मूलम्
> +यथ्स॒भायाँ᳚व्वि॒जय॑न्ते ।
>
> अस॑व्ँव्लयाय इति यथा भवता शोधितम्, तदेव साधु। मया +उपरि टङ्कनदोषः कृत
> आसीत्। अधुना शोधितः।
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/vvasuki/vedAH/pull/11#discussion_r567194152>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALIVMANVMFHRAUUQPQ3P6MTS4OBPNANCNFSM4VHGBAPQ>
> .
>

2021-01-30 09:49 UTC, vvasuki requested changes

2021-01-30 09:49 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/3.md
> +तङ् गा॑य॒त्र्या आह॑रत् ।
अत्र पूर्ववद् एव वरम् भाति।

2021-01-30 09:49 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/8.md
> +''घ॒र्मश् शिर॒'' इति॒ गार्ह॑पत्य॒म् आद॑धाति ।
"-इत्येव चिह्नम् प्रयोक्तव्यम्।

2021-01-31 03:49 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/7/4.md
> +<<<<<<< HEAD
अयं निष्कासितः

2021-01-31 03:49 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/7/1.md
> +<<<<<<< HEAD
अयमपि निष्कासितः

2021-01-31 03:50 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/3.md
> +तङ् गा॑य॒त्र्या आह॑रत् ।
समीकृतम्

2021-01-31 03:55 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/1/8.md
> +''घ॒र्मश् शिर॒'' इति॒ गार्ह॑पत्य॒म् आद॑धाति ।
परिवर्तितम्

2021-01-31 05:22 UTC, merged