2/1-3
vvasuki/vedAH pull request #48
Opened 2021-03-08 05:03 UTC by Veerasimha

2021-03-08 11:07 UTC, vvasuki requested changes
शोधनीयांशौ सूचितौ।

2021-03-08 11:07 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/7/2.md
> +वै॒ष्ण॒वन् त्रि॑कपा॒लम् । +++(निर्व॑पति)+++
दण्डात् पूर्वम् अध्याहृतम् पदं स्थापयतु।

2021-03-08 11:07 UTC, vvasuki commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/7/3..md
> +unicode_script: devanagari
सञ्चिकानाम्नि दोषः - बिन्दुर् अधिकः। एवम् अग्रेऽपि।

2021-03-11 09:52 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/7/2.md
> +वै॒ष्ण॒वन् त्रि॑कपा॒लम् । +++(निर्व॑पति)+++
समीकृतम्

2021-03-11 09:53 UTC, Veerasimha commented on content/taittirIyam/brAhmaNam/bhaTTa-bhAskara-bhAShyam/1/7/3..md
> +unicode_script: devanagari
बिन्दुदोषः समीकृतः

2021-03-13 00:11 UTC, merged